### ISSUE TITLE
GHL workstream 1

### ISSUE THREAD

**Issue by eckelj** [rddl-network/EnergyAgent#101]
zeige energie und power auch in mwh und mw

Schritte:

- [x] 1. Sinvolle Simulationsdaten bezueglich  kW und kWh Produktivitaet eines Solarkraftwerks und eines Windkraftwerks mit 5 Turbinen in 15 Minuten-Intervallen ueber einen Zeitraum von 24 Stunden
- [ ]  2. Abgreifen der Simulationsdsaten, die die Stromzufuhr zum Elektrolyseur simulieren.
- [ ]  3. Aufbauend auf Elektrolyseur CSV , Ermittlung der genauen Formel der Umrechnung von dem Elektrolyseur zugefuerhrten Energie aus einer oder mehreren Quellen in kg H2O und Output in mW Energie.  Entweder bekommen wir die detaillierte Formen oder wir arbeiten mit gemittelten Werten.
- [ ] 4. Erstellung eines prototypischen Zertifikats, das fuer jeden Batch produziertem Gruengas welche ereneuerbaren Enerquellen in welcher Energiemenge genutzt wurden.
- [ ] Das macht die Business Logik transparent und eindeutig nachvollziehbar.
