### ISSUE TITLE
GHL workstream 2

### ISSUE THREAD

**Issue by eckelj** [rddl-network/EnergyAgent#102]
Arbeitsstream 2 wir sich auf die transparente und vereinfachte Erstellung und Verkuepfung von Energie-Assets (Anlagen) mit Bloickchain wallets beziehen. Inklusiert klare Abgrenzung und Ausdiffrenzierung der AKteure und der Rollen. Energieproduzenten/Lieferanten und Gruengasproduzenten. Mit der Funktionalitaet Akteure/Anlagen hinzuzufuegen oder zu entfernen.

- [ ] 
- [ ] 1. Anlegen der Akteure auf der Blockchain mit einfach nachvollziehbarer Verknueofung von Key-Material, Blockchain-Adressen mit Klarnamen. Sowohl bei der Anlage der Akteure im System als auch am Dashboard, das alle Leistungsdaten visualisiert und protokolliert.
- [ ] 2. Erzeugung der dafuer notwendigen Eingabe-Masken
- [ ] 3. Adaptierung der Anzeigen der Produktionsdaten und zugehoerigen Akteure
- [ ] 4. Filtern der angezeigenten nach Akteur, Zeit, Batch, ...
- [ ] 5. Anlegen, loeschen und managen von Wallets fuer Drittpartner
- [ ] 6. Verknuepfung der Wallets, die die Anlagen und Drittfirmen repraesntieren mit mit den eingespeisten kWh-Token und den ausgespielten H2O-Tokens.
- [ ] 7. Konkreter Integrationsvorschlag ddes Wallet-Systems in die Datalake Umgebung.
